# ---------------------------
# Please use this file to configure variables for different environments
# such as dev, staging, prod etc
# ---------------------------

# The name of the project for all ClearML artifacts. It can be changed to create new project environment.
# Use alpha numeric names without spaces. e.g for production, use the name "Detection_Prod"
# NOTE: please use a different name to prevent inteference existing ClearML projects
project-name: "Detection"

# the initial dataset download location
base-dataset-url: "https://raw.githubusercontent.com/vanilla-ai-ml/large_datasets/main/dev_dataset.zip"

# the initial model download location. {} for model variant format, specific to YOLO
base-model-url: "https://github.com/ultralytics/assets/releases/download/v8.3.0/{}.pt"

