    epochs: 5
    imgsz: 640
    batch: 12
    lr0: 0.0006
    warmup_epochs: 3
    patience: 10
    verbose: True
    plots: True
    augment: True
    mosaic: 0
    mixup: 0
    degrees: 5
    translate: 0.05
    scale: 0.1
    shear: 0.0
    hsv_h: 0.005 
    hsv_s: 0.3
    hsv_v: 0.2